name: pastipark_mobile
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.4.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  google_fonts: 6.2.1
  get_storage: 2.1.1
  phosphor_flutter: 2.1.0
  http: 1.2.1
  dio: 5.4.3+1
  image_picker: 1.1.2
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/icons/
    - assets/icons/report/
    - assets/images/
    - assets/logo/
  uses-material-design: true

